version: "3"
services:
  
  api_server:
    build: ./
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    # environment:
    #   - 
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - service_app

networks:
  service_app: