version: "3.4"
services:
  
  api_server:
    build: ./
    ports:
      - "4444:4445"
    env_file:
      - ./.env
    # environment:
    #   - 
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - soanet

networks:
  soanet: